# basic options
title: The Livingroom
author: Diego Lassala
email: lassala.diego@gmail.com
description: A wonderful site to test my diary/blog
# twitter_username: Nanai
github_username:  diegolassala

# Build settings
markdown: kramdown
theme: minima
