# basic options
title: The Livingroom
  author: Diego Lassala
  email: your-email@domain.com
description: A wonderful site
twitter_username: Nanai
github_username:  diegolassala

# Build settings
markdown: kramdown
remote_theme: minima
